repos:
    # python import sorting - will amend files
    - repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.8.0
      hooks:
          - id: isort
            language_version: python3.9

    # python code formatting - will amend files
    - repo: https://github.com/ambv/black
      rev: 21.5b2
      hooks:
          - id: black
            language_version: python3.9

    # Flake8 includes pyflakes, pycodestyle, mccabe, pydocstyle, bandit
    - repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
          - id: flake8
            language_version: python3.9
            additional_dependencies: ["flake8-docstrings", "flake8-bandit", "flake8-print"]

    # python static type checking
    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.812
      hooks:
          - id: mypy
            language_version: python3.9
